vich_uploader:
    db_driver: orm

    mappings:
        categories:
            uri_prefix: '%app.path.categories_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.categories_images%'

        conseillers:
            uri_prefix: /images/conseillers
            upload_destination: '%kernel.project_dir%/public/images/conseillers'
